import cv2
import csv
# for version 1.0
from func4video import *

def read_csv(path, name):
    with open(path,"r",newline="", encoding="utf-8-sig", errors="ignore") as f:
        csv_write = csv.reader(f)
        list_stuff = []
        for i,row in enumerate(csv_write):
            if str(name) in row:
                list_stuff.append(row)
            else:
                continue
    return list_stuff


def main():
    flag_mask = 1
    video_path = "../sth_4_1/stream_2019_11_09_11_53_32.h264"
    csv_path = "../sth_4_1/ground_truth.csv"
    ####----------------points generated by functions.py
    mask_point = np.array([[0, 618], [228, 552], [393, 501], [514, 466], [604, 436], \
                    [680, 421], [732, 416], [765, 429], [830, 459], [1078, 594], \
                    [1279, 718], [0, 718]], dtype=np.int32)
    point1 = np.float32(np.array([[57, 626], [408, 517], [759, 481], [1059, 615], \
                    [962, 664], [684, 618], [360, 597]], dtype=np.int32)).reshape(-1,1,2)
    point2 = np.float32(np.array([[163, 181], [316,199], [474,296], [473,473], \
                    [418,469], [358,363], [266,248]], dtype=np.int32)).reshape(-1,1,2)
    ####----------------
    file_name = video_path.split("/")[-1].split(".")[-2]
    # print(file_name)
    list_stuff = read_csv(csv_path, file_name)
    # print(list_stuff)
    for i in list_stuff:
        # print(i)
        file_name = str(i[0])
        clip_num_new = str(i[1])
        time1 = int(i[2])
        time2 = int(i[3])
        old_capture = cv2.VideoCapture(video_path)
        fps_old = 30
        size_old = (1280, 720)
        new_path = "../sth_4_1/"+file_name+"-clip_num-"+str(clip_num_new)+".mp4"
        videoWriter = cv2.VideoWriter(new_path,cv2.VideoWriter_fourcc('X','V','I','D'),fps_old,size_old)


        ii = 0
        while True:
            success,frame = old_capture.read()
            if success:
                if flag_mask==True:
                    #-----
                    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                    frame = add_mask(mask_point, frame_rgb)
                    #-----
                ii += 1
                if ii>=int(time1) and ii<int(time2):
                    videoWriter.write(frame)
            else:
                print(str(clip_num_new),"transform finished")
                break
    print(">>>>>-----crop finished------<<<<<")
if __name__=="__main__":
    main()
